### ISSUE TITLE
Problem entering workflow steps

### ISSUE THREAD

**Issue by bixwilson** [xtuple/xtuple#1970] opened 2014-10-28 15:53 UTC
Creating new workflow steps in web client. Version 4.7.0. Chrome browser on Mac OSX 10.9.5 (Mavericks, I think).

I enter one workflow step and click "Checkmark" button. At this point I see the list of steps with one step in it (the one I just created). 
I click PLUS to enter another step. Fill in fields and click CHECK. Now there are two steps in the list.
I click PLUS to enter a third step. The editor opens with the data from the previous step in the fields. I replace the data and click CHECK. Get error message that "name is required." Cannot save step. Eventually have to log out and go back to that screen to enter the final step.

**Comment by gpazo** [comment] 2015-06-25 15:46
closing, cannot reproduce.

**Closed by gpazo** 2015-06-25 15:46 UTC
