### ISSUE TITLE
Selection of 31st day in the date picker widget converts to 1st date of that month

### ISSUE THREAD

**Issue by amikheychik** [xtuple/xtuple#1979] opened 2014-11-03 16:48 UTC
Step to reproduce:

1. Create a worksheet.
2. Select 10/31 or 12/31 in the date picker for the field "Week of"
3. Field "Week of" will be 10/1 (or 12/1)

Notes:
+ This bug happens only for 31st. For 30th and 28th (of February) it works correct.
+ This bug happens for any date picker so far.

Screenshot:
+ https://www.dropbox.com/s/6s9rwo54l0dcmly/shj8i-s0w2e-mz53g-u6qn9.jpg.jpg?dl=0

**Comment by gpazo** [comment] 2015-06-18 20:08
closing as dupe of #2159

**Closed by gpazo** 2015-06-18 20:08 UTC

**Comment by amikheychik** [comment] 2015-06-18 21:52
@gpazo it's #2159 is a duplicate of this one! :smile:
